Development
Mechetel/codebreaker_console pull request #1
Opened 2021-03-20 12:02 UTC by Mechetel

2021-04-12 11:43 UTC, valter0ff commented on entities/console.rb
> +end
You can remove begin keyword (and end too), because this block is inside method definition
https://rubystyle.guide/#begin-implicit

2021-04-12 18:47 UTC, Win9XCHI approved these changes

2021-04-12 18:47 UTC, Win9XCHI commented on entities/console.rb
> +    system 'clear'
Don't need to use it

2021-04-12 18:47 UTC, Win9XCHI commented on modules/questioner.rb
> +    case input
`case gets.chomp`

2021-04-12 18:47 UTC, Win9XCHI commented on services/registrator_service.rb
> +      user = Codebreaker::User.new(input)
Instead `input` -> `gets.chomp`

2021-04-12 19:00 UTC, etherell commented on entities/console.rb
> +    if @game.no_hints?
you can use guard clouse here:
```ruby
return puts I18n.t('no_hints') if @game.no_hints?

puts(I18n.t('show_hint') + @game.use_hint.to_s)
```

2021-04-12 19:00 UTC, etherell commented on entities/console.rb
> +    won if @game.win?(guess)
Don't you need return here?
`return won if @game win?(guess)`

2021-04-12 19:00 UTC, etherell commented on spec/entities/console_spec.rb
> +    it 'sets game instance variable' do
where is expect here?

2021-04-12 19:00 UTC, etherell commented on spec/entities/console_spec.rb
> +    it 'sets game instance variable' do
where is expect here?

2021-04-12 19:00 UTC, etherell commented on spec/entities/console_spec.rb
> +      it 'receive lost method' do
where is expect here?

2021-04-12 19:00 UTC, etherell commented on spec/modules/console_questioner_spec.rb
> +      it 'call rules method' do
Please check if all tests have expect

2021-04-13 12:30 UTC, valter0ff approved these changes
Good job

2021-04-13 12:49 UTC, etherell approved these changes

2021-04-15 07:59 UTC, Dimasfullxq requested changes
clean your specs, by adding all allow methods to before

2021-04-15 07:59 UTC, Dimasfullxq commented on .rubocop.yml
> +    - 'spec/**/*'
redundant

2021-04-15 07:59 UTC, Dimasfullxq commented on Gemfile
> +gem 'simplecov'
versions

2021-04-15 07:59 UTC, Dimasfullxq commented on entities/console.rb
> +    return if error.nil?
unless

2021-04-15 07:59 UTC, Dimasfullxq commented on spec/entities/console_spec.rb
> +      allow(console).to receive(:ask_choose_game_option)
move all allows to before pls

2021-04-15 07:59 UTC, Dimasfullxq commented on spec/entities/console_spec.rb
> +                      "=========================\n").to_stdout
use your service logic

2021-04-15 07:59 UTC, Dimasfullxq commented on spec/entities/console_spec.rb
> +        game.instance_variable_set(:@hints_list, [1, 2])
before

2024-08-03 11:17 UTC, merged